---
Name: downloadableproductsconfig
After: '#rootroutes'
---
Director:
  rules:
    'assets/downloadable': 'DownloadableFileController'
Checkout_Controller:
  extensions:
    - DownloadableCheckoutExtension
OrderItem:
  extensions:
    - DownloadableOrderItemExtension
